version: '2'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=docker

  mongo:
    image: mongo
    restart: always

  redis:
    image: redis
    restart: always
